package com.aicardgrader.app.ui

import androidx.compose.foundation.Image
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedButton
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.asImageBitmap
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.unit.dp
import com.aicardgrader.app.CardGraderViewModel
import com.aicardgrader.app.data.toEstimates
import com.aicardgrader.app.grading.SubGrades
import com.aicardgrader.app.ui.components.GradeBadge
import com.aicardgrader.app.ui.components.SubgradeBars
import com.aicardgrader.app.ui.components.rememberBitmapFromFile

@Composable
fun HistoryDetailScreen(
    viewModel: CardGraderViewModel,
    recordId: Long,
    onDeleted: () -> Unit
) {
    val record by viewModel.recordFlow(recordId).collectAsState(initial = null)
    val current = record ?: run {
        Text("Card not found.", modifier = Modifier.padding(24.dp))
        return
    }

    val front = rememberBitmapFromFile(current.frontImagePath)
    val back = rememberBitmapFromFile(current.backImagePath)

    LazyColumn(
        modifier = Modifier
            .fillMaxSize()
            .padding(horizontal = 20.dp),
        verticalArrangement = Arrangement.spacedBy(16.dp)
    ) {
        item { Spacer(Modifier.height(12.dp)) }
        item { Text(current.cardName, style = MaterialTheme.typography.titleLarge) }

        item {
            Row(horizontalArrangement = Arrangement.spacedBy(12.dp)) {
                front?.let {
                    Image(
                        bitmap = it.asImageBitmap(),
                        contentDescription = "Front of card",
                        contentScale = ContentScale.Crop,
                        modifier = Modifier
                            .weight(1f)
                            .height(180.dp)
                            .clip(RoundedCornerShape(12.dp))
                    )
                }
                back?.let {
                    Image(
                        bitmap = it.asImageBitmap(),
                        contentDescription = "Back of card",
                        contentScale = ContentScale.Crop,
                        modifier = Modifier
                            .weight(1f)
                            .height(180.dp)
                            .clip(RoundedCornerShape(12.dp))
                    )
                }
            }
        }

        item {
            Text("Category breakdown", style = MaterialTheme.typography.titleMedium)
            SubgradeBars(
                SubGrades(
                    centering = current.centering,
                    corners = current.corners,
                    edges = current.edges,
                    surface = current.surface
                )
            )
        }

        item { Text("Estimated grades by company", style = MaterialTheme.typography.titleMedium) }

        items(current.toEstimates()) { estimate -> GradeBadge(estimate) }

        item {
            Text(
                "Estimates only, generated by on-device image analysis. Not official, submitted, or certified grades, and not affiliated with or endorsed by PSA, Beckett/BGS, CGC, or SGC.",
                style = MaterialTheme.typography.bodyMedium,
                color = MaterialTheme.colorScheme.onBackground.copy(alpha = 0.6f)
            )
        }

        item {
            OutlinedButton(
                onClick = {
                    viewModel.deleteRecord(current)
                    onDeleted()
                },
                modifier = Modifier.fillMaxWidth()
            ) { Text("Delete this card") }
            Spacer(Modifier.height(24.dp))
        }
    }
}
