package com.aicardgrader.app.ui

import androidx.compose.foundation.Image
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.Button
import androidx.compose.material3.Card
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.asImageBitmap
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import com.aicardgrader.app.CardGraderViewModel
import com.aicardgrader.app.data.displayName
import com.aicardgrader.app.data.toEstimatesUi
import com.aicardgrader.app.ui.components.GradeBadge
import com.aicardgrader.app.ui.components.SubgradeBars

@Composable
fun ResultsScreen(
    viewModel: CardGraderViewModel,
    onGradeAnother: () -> Unit,
    onDone: () -> Unit
) {
    val result = viewModel.currentResult ?: run {
        Text("No result available.", modifier = Modifier.padding(24.dp))
        return
    }
    val front = viewModel.frontBitmap
    val back = viewModel.backBitmap
    val suggestedName = viewModel.suggestedCardName
    var cardName by remember(suggestedName) { mutableStateOf(suggestedName ?: "") }
    var saved by remember { mutableStateOf(false) }

    LazyColumn(
        modifier = Modifier
            .fillMaxWidth()
            .padding(horizontal = 20.dp),
        verticalArrangement = Arrangement.spacedBy(16.dp)
    ) {
        item { Spacer(Modifier.height(12.dp)) }

        item {
            Row(horizontalArrangement = Arrangement.spacedBy(12.dp)) {
                front?.let {
                    Image(
                        bitmap = it.asImageBitmap(),
                        contentDescription = "Front of card",
                        contentScale = ContentScale.Crop,
                        modifier = Modifier
                            .weight(1f)
                            .height(180.dp)
                            .clip(RoundedCornerShape(12.dp))
                    )
                }
                back?.let {
                    Image(
                        bitmap = it.asImageBitmap(),
                        contentDescription = "Back of card",
                        contentScale = ContentScale.Crop,
                        modifier = Modifier
                            .weight(1f)
                            .height(180.dp)
                            .clip(RoundedCornerShape(12.dp))
                    )
                }
            }
        }

        if (result.confidence.reasons.isNotEmpty()) {
            item {
                Card(modifier = Modifier.fillMaxWidth()) {
                    Column(modifier = Modifier.padding(14.dp)) {
                        Text(
                            "${result.confidence.level.displayName()} — tips for a better read:",
                            fontWeight = FontWeight.SemiBold,
                            style = MaterialTheme.typography.bodyMedium
                        )
                        result.confidence.reasons.forEach {
                            Text("• $it", style = MaterialTheme.typography.bodyMedium)
                        }
                    }
                }
            }
        }

        item {
            Text("Category breakdown", style = MaterialTheme.typography.titleMedium)
            SubgradeBars(result.subGrades)
        }

        item {
            Text("Estimated grades by company", style = MaterialTheme.typography.titleMedium)
        }

        items(result.toEstimatesUi()) { estimate ->
            GradeBadge(estimate)
        }

        item {
            Text(
                "Estimates only, generated by on-device image analysis. Not official, submitted, or certified grades, and not affiliated with or endorsed by PSA, Beckett/BGS, CGC, or SGC.",
                style = MaterialTheme.typography.bodyMedium,
                color = MaterialTheme.colorScheme.onBackground.copy(alpha = 0.6f)
            )
        }

        item {
            if (!saved) {
                OutlinedTextField(
                    value = cardName,
                    onValueChange = { cardName = it },
                    label = { Text("Name this card (optional)") },
                    modifier = Modifier.fillMaxWidth()
                )
                if (!suggestedName.isNullOrBlank()) {
                    Text(
                        "Detected on-device from the photo — edit if it's not quite right.",
                        style = MaterialTheme.typography.bodyMedium,
                        color = MaterialTheme.colorScheme.onBackground.copy(alpha = 0.6f)
                    )
                }
                Spacer(Modifier.height(8.dp))
                Button(
                    onClick = {
                        viewModel.saveToHistory(cardName) { saved = true }
                    },
                    modifier = Modifier.fillMaxWidth()
                ) { Text("Save to history") }
            } else {
                Text("Saved to history.", style = MaterialTheme.typography.bodyMedium)
            }
            Spacer(Modifier.height(8.dp))
            Button(onClick = onGradeAnother, modifier = Modifier.fillMaxWidth()) {
                Text("Grade another card")
            }
            Spacer(Modifier.height(8.dp))
            Button(onClick = onDone, modifier = Modifier.fillMaxWidth()) {
                Text("Done")
            }
            Spacer(Modifier.height(24.dp))
        }
    }
}
